WebApp/Models/Group.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApp.Models;

public partial class Group
{
    public int Id { get; set; }

    public int? CourseId { get; set; }

    [Required]
    [StringLength(10)]
    public string Name { get; set; } = null!;

    [NotMapped]
    public SelectList? Courses { get; set; }

    public virtual Course? Course { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}

WebApp/Models/Student.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApp.Models;

public partial class Student
{
    public int Id { get; set; }

    public int? GroupId { get; set; }

    [Required]
    [StringLength(50)]
    [RegularExpression(@"[a-zA-Z]+", ErrorMessage = "The field is letter only.")]
    public string FirstName { get; set; } = null!;

    [Required]
    [StringLength(50)]
    [RegularExpression(@"[a-zA-Z]+", ErrorMessage = "The field is letter only.")]
    public string LastName { get; set; } = null!;
    
    [NotMapped]
    public SelectList? Groups { get; set; }

    public virtual Group? Group { get; set; }
}

WebApp/Controllers/GroupController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Elfie.Serialization;
using WebApp.Models;
using WebApp.Services;
using WebApp.Services.Interfaces;

namespace WebApp.Controllers;

public class GroupController : Controller
{
    private readonly IGroupService _groupService;
    private readonly List<Group> _groups;

    public GroupController(IGroupService groupService)
    {
        _groupService = groupService;
        _groups = groupService.GetAll().ToList();
    }

    public IActionResult Index()
    {
        return View(_groups);
    }

    [Route("[controller]/{groupId:int}")]
    public IActionResult Students(int groupId)
    {
        var students = _groupService.GetStudents(groupId).ToList();
        
        if (students.Count == 0)
        {
            students.Add(new Student()
            {
                Group = _groups.FirstOrDefault(x => x.Id == groupId)
            });
        }
        
        return View(students);
    }
    
    [Route("[controller]/{groupId:int}/[action]")]
    public IActionResult Edit(int groupId)
    {
        var group = _groups.FirstOrDefault(x => x.Id == groupId);
        
        return View(group);
    }
}

WebApp/Controllers/GroupsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApp.Controllers;

public class GroupsController : Controller
{
    private readonly IGroupService<Group> _groupService;
    private readonly ICourseService<Course> _courseService;
    private readonly ICancelable _cancelService;

    public GroupsController(
        IGroupService<Group> groupService,
        ICourseService<Course> courseService,
        ICancelable cancelService)
    {
        _groupService = groupService;
        _courseService = courseService;
        _cancelService = cancelService;
    }

    public async Task<IActionResult> IndexAsync()
    {
        var groups = await _groupService.GetAllAsync() as List<Group>;
        return View("Index", groups);
    }

    public async Task<IActionResult> StudentsAsync(int groupId)
    {
        var groupStudents = await _groupService.GetGroupStudentsAsync(groupId) as List<Student>;
        var groups = await _groupService.GetAllAsync();
        
        ViewData["GroupName"] = groups.FirstOrDefault(x => x.Id == groupId)!.Name;

        return View("Students", groupStudents);
    }
    
    public async Task<IActionResult> EditAsync(int groupId)
    {
        _cancelService.ViewDataReferer(ViewData, Request);

        var groups = await _groupService.GetAllAsync();
        var group = groups.FirstOrDefault(x => x.Id == groupId);
        
        if (group != null)
        {
            return View("Edit", group);
        }

        return NotFound();
    }
    
    [HttpPost]
    public async Task<IActionResult> EditAsync(Group group)
    {
        if (ModelState.IsValid)
        {
            await _groupService.UpdateAsync(group);
            return RedirectToAction("Index");
        }

        return BadRequest();
    }
    
    public async Task<IActionResult> AddAsync()
    {
        _cancelService.ViewDataReferer(ViewData, Request);
        
        var group = new Group
        {
            Courses = new SelectList(await _courseService.GetAllAsync(), "Id", "Name")
        };
        
        return View("Add", group);
    }

    [HttpPost]
    public async Task<IActionResult> AddAsync(Group group)
    {
        if (ModelState.IsValid)
        {
            await _groupService.AddAsync(group);
            return RedirectToAction("Index");
        }
        
        return BadRequest();
    }

    [HttpPost]
    public async Task<IActionResult> DeleteAsync(Group group)
    {
        if (group.Students.Count == 0)
        {
            await _groupService.DeleteAsync(group);
        }

        return RedirectToAction("Index");
    }
}

WebApp/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApp.Services;
using WebApp.Services.Interfaces;

namespace WebApp.Controllers;

public class StudentController : Controller
{
    private readonly IStudentService _studentService;

    public StudentController(IStudentService studentService)
    {
        _studentService = studentService;
    }

    public IActionResult Index()
    {
        var students = _studentService.GetAll().ToList();
        return View(students);
    }
}

WebApp/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApp.Controllers;

public class StudentsController : Controller
{
    private readonly IService<Student> _studentService;
    private readonly IGroupService<Group> _groupService;
    private readonly ICancelable _cancelService;

    public StudentsController(
        IService<Student> studentService,
        IGroupService<Group> groupService,
        ICancelable cancelService)
    {
        _studentService = studentService;
        _groupService = groupService;
        _cancelService = cancelService;
    }

    public async Task<IActionResult> IndexAsync()
    {
        var students = await _studentService.GetAllAsync() as List<Student>;
        return View("Index", students);
    }
    
    public async Task<IActionResult> EditAsync(int studentId)
    {
        _cancelService.ViewDataReferer(ViewData, Request);

        var students = await _studentService.GetAllAsync();
        var student = students.FirstOrDefault(x => x.Id == studentId);

        if (student != null)
        {
            return View("Edit", student);
        }

        return NotFound();
    }
    
    [HttpPost]
    public async Task<IActionResult> EditAsync(Student student)
    {
        if (ModelState.IsValid)
        {
            await _studentService.UpdateAsync(student);
            return RedirectToAction("Index");
        }

        return BadRequest();
    }
    
    public async Task<IActionResult> AddAsync()
    {
        _cancelService.ViewDataReferer(ViewData, Request);
        
        var student = new Student
        {
            Groups = new SelectList(await _groupService.GetAllAsync(), "Id", "Name")
        };
        
        return View("Add", student);
    }

    [HttpPost]
    public async Task<IActionResult> AddAsync(Student student)
    {
        if (ModelState.IsValid)
        {
            await _studentService.AddAsync(student);
            return RedirectToAction("Index");
        }
        
        return BadRequest();
    }

    [HttpPost]
    public async Task<IActionResult> DeleteAsync(Student student)
    {
        await _studentService.DeleteAsync(student);
        return RedirectToAction("Index");
    }
}

WebApp/Views/Groups/Add.cshtml
@model Group

@{
    ViewBag.Title = "Add new group";
    Layout = "_Layout";
}

<div class="mx-auto col-10 col-md-8 col-lg-6">
    
    <h2>Add new group</h2>

    <form method="post" asp-controller="Groups" asp-action="Add">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row mb-2">
            <label asp-for="Name" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-10">
                <input asp-for="Name" class="form-control" type="text"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row mb-2">
            <label asp-for="CourseId" class="col-sm-2 col-form-label">Course</label>
            <div class="col-sm-10">
                <select asp-for="CourseId" class="form-select" asp-items="@Model.Courses"></select>
            </div>
        </div>
        <div class="d-flex flex-row-reverse">
            @if (!string.IsNullOrEmpty(ViewData["Referer"]!.ToString()))
            {
                <a class="btn btn-outline-danger" href="@ViewData["Referer"]">Cancel</a>
            }
            <button type="submit" class="btn btn-primary mx-2">Save</button>
        </div>
    </form>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/Groups/Edit.cshtml
@model Group

@{
    ViewBag.Title = "Edit " + Model.Name;
    Layout = "_Layout";
}

<div class="mx-auto col-10 col-md-8 col-lg-6">
    
    <h2>@Model.Name</h2>

    <form method="post" asp-controller="Groups" asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row mb-2">
            <label asp-for="Id" class="col-sm-2 col-form-label">Id</label>
            <div class="col-sm-10">
                <input asp-for="Id" readonly class="form-control" type="text" placeholder="@Model.Id"/>
            </div>
        </div>
        <div class="form-group row mb-2">
            <label asp-for="Name" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-10">
                <input asp-for="Name" class="form-control" type="text" value="@Model.Name"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row mb-2">
            <label class="col-sm-2 col-form-label">Course</label>
            <div class="col-sm-10">
                <input readonly class="form-control" type="text" placeholder="@Model.Course!.Name"/>
            </div>
        </div>
        <div class="d-flex flex-row-reverse">
            @if (!string.IsNullOrEmpty(ViewData["Referer"]!.ToString()))
            {
                <a class="btn btn-outline-danger" href="@ViewData["Referer"]">Cancel</a>
            }
            <button type="submit" class="btn btn-primary mx-2">Save</button>
        </div>
    </form>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/Groups/Index.cshtml
@model List<Group>

@{
    ViewBag.Title = "Groups";
    Layout = "_Layout";
}

<h2>Groups</h2>

<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Course</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var group in Model)
    {
        <tr>
            <th scope="row">@group.Id</th>
            <td>@group.Name</td>
            <td>@group.Course!.Name</td>
            <td>
                <div class="d-flex flex-row">
                    <a class="btn btn-primary" asp-controller="Groups" asp-action="Students" asp-route-groupId="@group.Id">Students</a>
                    <a class="btn btn-primary mx-2" asp-controller="Groups" asp-action="Edit" asp-route-groupId="@group.Id">Edit</a>
                    @using (Html.BeginForm("Delete", "Groups", new { groupId = group.Id }))
                    {
                        <button type="submit" class="btn btn-danger">Delete</button>
                    }
                </div>
            </td>
        </tr>
    }
    </tbody>
</table>

<div id="btn-fix">
    <a class="btn btn-primary btn-square-md rounded-circle" asp-controller="Groups" asp-action="Add">
        <h1><i class="bi bi-person-plus-fill"></i></h1>
    </a>
</div>

WebApp/Views/Groups/Students.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model List<Student>

@{
    var groupName = ViewData["GroupName"]!.ToString();
    ViewBag.Title = groupName!;
    Layout = "_Layout";
}

<h2>@groupName</h2>

@if (Model.Count == 0)
{
    <h3>The group is empty</h3>
}
else
{
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Group</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var student in Model)
        {
            <tr>
                <th scope="row">@student.Id</th>
                <td>@student.FirstName</td>
                <td>@student.LastName</td>
                <td>@student.Group!.Name</td>
                <td>
                    <div class="d-flex flex-row">
                        <a class="btn btn-primary mx-2" asp-controller="Students" asp-action="Edit" asp-route-studentId="@student.Id">Edit</a>
                        @using (Html.BeginForm("Delete", "Students", new { studentId = student.Id }))
                        {
                            <button type="submit" class="btn btn-danger">Delete</button>
                        }
                    </div>
                </td>
            </tr>
        }
        </tbody>
    </table>
}

<div id="btn-fix">
    <a class="btn btn-primary btn-square-md rounded-circle" asp-controller="Students" asp-action="Add">
        <h1><i class="bi bi-person-plus-fill"></i></h1>
    </a>
</div>