WebApp/Models/Course.cs
using System.ComponentModel.DataAnnotations;

namespace WebApp.Models;

public partial class Course
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string? Description { get; set; }

    public virtual ICollection<Group> Groups { get; set; } = new List<Group>();
}

WebApp/Models/Group.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApp.Models;

public partial class Group
{
    public int Id { get; set; }

    public int? CourseId { get; set; }

    [Required]
    [StringLength(10)]
    public string Name { get; set; } = null!;

    [NotMapped]
    public SelectList? Courses { get; set; }

    public virtual Course? Course { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}

WebApp/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using WebApp.Services;
using WebApp.Services.Interfaces;

namespace WebApp.Controllers;

public class CourseController : Controller
{
    private readonly ICourseService _courseService;
    private readonly List<Course?> _courses;

    public CourseController(ICourseService courseService)
    {
        _courseService = courseService;
        _courses = courseService.GetAll().ToList();
    }

    public IActionResult Index()
    {
        return View(_courses);
    }

    [Route("[controller]/{courseId:int}")]
    public IActionResult Groups(int courseId)
    {
        var groups = _courseService.GetGroups(courseId).ToList();

        if (groups.Count == 0)
        {
            groups.Add(new Group()
            {
                Course = _courses.FirstOrDefault(x => x!.Id == courseId)
            });
        }
        
        return View(groups);
    }
}

WebApp/Controllers/GroupController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Elfie.Serialization;
using WebApp.Models;
using WebApp.Services;
using WebApp.Services.Interfaces;

namespace WebApp.Controllers;

public class GroupController : Controller
{
    private readonly IGroupService _groupService;
    private readonly List<Group> _groups;

    public GroupController(IGroupService groupService)
    {
        _groupService = groupService;
        _groups = groupService.GetAll().ToList();
    }

    public IActionResult Index()
    {
        return View(_groups);
    }

    [Route("[controller]/{groupId:int}")]
    public IActionResult Students(int groupId)
    {
        var students = _groupService.GetStudents(groupId).ToList();
        
        if (students.Count == 0)
        {
            students.Add(new Student()
            {
                Group = _groups.FirstOrDefault(x => x.Id == groupId)
            });
        }
        
        return View(students);
    }
    
    [Route("[controller]/{groupId:int}/[action]")]
    public IActionResult Edit(int groupId)
    {
        var group = _groups.FirstOrDefault(x => x.Id == groupId);
        
        return View(group);
    }
}

WebApp/Controllers/GroupsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApp.Controllers;

public class GroupsController : Controller
{
    private readonly IGroupService<Group> _groupService;
    private readonly ICourseService<Course> _courseService;
    private readonly ICancelable _cancelService;

    public GroupsController(
        IGroupService<Group> groupService,
        ICourseService<Course> courseService,
        ICancelable cancelService)
    {
        _groupService = groupService;
        _courseService = courseService;
        _cancelService = cancelService;
    }

    public async Task<IActionResult> IndexAsync()
    {
        var groups = await _groupService.GetAllAsync() as List<Group>;
        return View("Index", groups);
    }

    public async Task<IActionResult> StudentsAsync(int groupId)
    {
        var groupStudents = await _groupService.GetGroupStudentsAsync(groupId) as List<Student>;
        var groups = await _groupService.GetAllAsync();
        
        ViewData["GroupName"] = groups.FirstOrDefault(x => x.Id == groupId)!.Name;

        return View("Students", groupStudents);
    }
    
    public async Task<IActionResult> EditAsync(int groupId)
    {
        _cancelService.ViewDataReferer(ViewData, Request);

        var groups = await _groupService.GetAllAsync();
        var group = groups.FirstOrDefault(x => x.Id == groupId);
        
        if (group != null)
        {
            return View("Edit", group);
        }

        return NotFound();
    }
    
    [HttpPost]
    public async Task<IActionResult> EditAsync(Group group)
    {
        if (ModelState.IsValid)
        {
            await _groupService.UpdateAsync(group);
            return RedirectToAction("Index");
        }

        return BadRequest();
    }
    
    public async Task<IActionResult> AddAsync()
    {
        _cancelService.ViewDataReferer(ViewData, Request);
        
        var group = new Group
        {
            Courses = new SelectList(await _courseService.GetAllAsync(), "Id", "Name")
        };
        
        return View("Add", group);
    }

    [HttpPost]
    public async Task<IActionResult> AddAsync(Group group)
    {
        if (ModelState.IsValid)
        {
            await _groupService.AddAsync(group);
            return RedirectToAction("Index");
        }
        
        return BadRequest();
    }

    [HttpPost]
    public async Task<IActionResult> DeleteAsync(Group group)
    {
        if (group.Students.Count == 0)
        {
            await _groupService.DeleteAsync(group);
        }

        return RedirectToAction("Index");
    }
}

WebApp/Views/Course/Groups.cshtml
@model List<Group>

@{
    ViewBag.Title = Model[0].Course!.Name;
    Layout = "_Layout";
}

<h2>@Model[0].Course!.Name</h2>

<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Course</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var group in Model)
    {
        <tr>
            <th scope="row">@group.Id</th>
            <td>@group.Name</td>
            <td>@group.Course!.Name</td>
            <td>
                <a class="btn btn-primary" asp-controller="Group" asp-action="Students" asp-route-groupId="@group.Id">Students</a>
                <button type="button" class="btn btn-primary">Edit</button>
                <button type="button" class="btn btn-danger">Delete</button>
            </td>
        </tr>
    }
    </tbody>
</table>

<div id="btn-fix">
    <button class="btn btn-primary btn-square-md rounded-circle"><h1><i class="bi bi-person-plus-fill"></i></h1></button>
</div>

WebApp/Views/Course/Index.cshtml
@model List<Course>

@{
    ViewBag.Title = "Courses";
    Layout = "_Layout";
}

<h2>Courses</h2>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var course in Model)
        {
            <tr>
                <th scope="row">@course.Id</th>
                <td>@course.Name</td>
                <td>@course.Description</td>
                <td>
                    <a class="btn btn-primary" asp-controller="Course" asp-action="Groups" asp-route-courseId="@course.Id">Groups</a>
                </td>
            </tr>
        }
    </tbody>
</table>